services:
  - type: web
    name: census-income-predictor
    env: python
    buildCommand: pip install -r app/requirements.txt
    startCommand: cd app && gunicorn -k uvicorn.workers.UvicornWorker main:app
    envVars:
      - key: PYTHON_VERSION
        value: 3.8
    healthCheckPath: /
    autoDeploy: true